# your domain
domain: 127.0.0.1
port:                 # default 12580

# source list file
source-files:
  # use local file
  - /root/proxypool/config/source.yaml
  #- ./config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml
  - https://raw.githubusercontent.com/shoujiyanxishe/atu/main/etproxypool.list

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# interval between each crawling
crawl-interval:    600   # v0.5.x default 60 (minutes)
crontime:          600   # v0.4.x default 60 (minutes). Deprecated in the newest version
healthcheck-connection:  500  # v0.7.2 default 500
healthcheck-timeout: 8 # default 5 (seconds)

# speed test
speedtest: false      # default false. Warning: this will consume large network resources.
#speedtest: true      # default false. Warning: this will consume large network resources.
speedtest-interval: 880  # default 720 (min)
speed-timeout:      10  # default 10 (seconds).
speed-connection:   20  # v0.7.2 default 5
connection:         20  # default 5. The number of speed test connections simultaneously
## active proxy speed test
active-interval:   260    # default 60 (min)
active-frequency:  100   # default 100 (requests per interval)
active-max-number: 100   # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
